workflow:
  rules:
    - if: $CI_USE_CUSTOM_RUNNER == "yes"
      # if this CI variable is defined then we use the private ubports runner
      variables:
        RUNNER_TAG: "ubports"
    - when: always
      # otherwise we fall back on this gitlab runner (this should be more or less the "default" runner config)
      variables:
        RUNNER_TAG: "saas-linux-small-amd64"

default:
  image: python:3.12
  tags:
    - $RUNNER_TAG

stages:
  - periodic
  - build

build-job:
  stage: build
  script:
    - echo "Build documentation"
    - echo "CI_PROJECT_NAMESPACE=$CI_PROJECT_NAMESPACE"
    - echo "CI_USE_CUSTOM_RUNNER=$CI_USE_CUSTOM_RUNNER"
    - echo "RUNNER_TAG=$RUNNER_TAG"
    - python --version
    - pip --version
    - pip install --no-cache-dir --user --upgrade -r requirements.txt
    - python -m sphinx -Wab html . _build/html
    - git fetch origin master:master
    - python3 -m sphinx -Wab rediraffecheckdiff . _build/html # check redirects against the master branch
    - echo "Build succeeded, browse the artifact here:" "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/_build/html/index.html"
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  artifacts:
    untracked: true
    when: on_success
    access: all
    expire_in: 90 days

periodic-job:
  stage: periodic
  script:
    - echo "Update translation pot file"
    - echo "CI_PROJECT_NAMESPACE=$CI_PROJECT_NAMESPACE"
    - echo "CI_USE_CUSTOM_RUNNER=$CI_USE_CUSTOM_RUNNER"
    - echo "RUNNER_TAG=$RUNNER_TAG"
    - python --version
    - pip --version
    - pip install --no-cache-dir --user --upgrade -r requirements.txt
    - bash ci-update-translations.sh
    - echo "Translation pot file update completed"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

